export function drawMetrics(app,kind){
 const c=document.getElementById(kind==='availability'?'canvasDailyAvailability':'canvasLatency');if(!c)return;const r=c.parentElement.getBoundingClientRect();if(r.width<10)return;const d=Math.min(devicePixelRatio||1,1.5);c.width=r.width*d;c.height=r.height*d;const x=c.getContext('2d');x.scale(d,d);const w=r.width,h=r.height;x.font='11px Segoe UI';x.fillStyle='#8098b1';
 const result=app.simulationResult;if(!result){x.fillText('Расчёт сценария…',14,h/2);return;}
 if(kind==='availability'){const steps=result.timeline_steps;const left=30,right=w-12,top=20,bottom=h-25;for(let i=0;i<3;i++){const y=top+(bottom-top)*i/2;x.strokeStyle='#233144';x.beginPath();x.moveTo(left,y);x.lineTo(right,y);x.stroke();x.fillText(i===0?'100':i===1?'50':'0',0,y+4);}for(let i=0;i<5;i++)x.fillText(String(i*6).padStart(2,'0')+':00',left+(right-left)*i/4-12,h-5);x.beginPath();for(let i=0;i<steps.length;i++){const px=left+i/(steps.length-1)*(right-left),py=steps[i].clients.C65?.available?top:bottom;if(i===0)x.moveTo(px,py);else{x.lineTo(px,i?steps[i-1].clients.C65?.available?top:bottom:py);x.lineTo(px,py);}}x.strokeStyle='#9dd8fb';x.lineWidth=2;x.stroke();x.lineTo(right,bottom);x.lineTo(left,bottom);x.closePath();const grad=x.createLinearGradient(0,top,0,bottom);grad.addColorStop(0,'#82bfea25');grad.addColorStop(1,'#82bfea02');x.fillStyle=grad;x.fill();
 }else{const ids=['C65','C70','C72'],names=['Урал-Север','Диксон','Тикси'];const vals=ids.map(id=>result.summary_metrics[id]?.avg_latency_ms);const max=Math.max(1,...vals.filter(v=>v!=null))*1.2;for(let i=0;i<3;i++){const y=20+i*(h-24)/3;x.fillStyle='#93a8bf';x.fillText(names[i],0,y+12);x.fillStyle='#1c2b3d';x.fillRect(88,y,w-154,14);x.fillStyle=['#a9d8ff','#7db8e4','#5486b0'][i];x.fillRect(88,y,(w-154)*(vals[i]||0)/max,14);x.fillStyle='#c8dff4';x.fillText(vals[i]==null?'—':vals[i].toFixed(1),w-53,y+12);}}
 const m=result.summary_metrics.C65||{},sc=result.effective_scenario;document.getElementById('kpiLatency').textContent=m.avg_latency_ms==null?'—':m.avg_latency_ms.toFixed(1)+' мс';document.getElementById('kpiSelfHealing').textContent=(m.max_outage_min??'—')+' мин';document.getElementById('kpiSatCount').textContent=sc.design.satellites.filter(s=>s.launch_batch<=sc.design.launch_stage).length;document.getElementById('kpiAvailability').textContent=(m.availability_percent??'—')+'%';
 if(app.comparisonMetric){const base=app.comparisonMetric,delta=(m.availability_percent-base.availability_percent);document.getElementById('comparisonResult').textContent=`К зафиксированному варианту: ${delta>=0?'+':''}${delta.toFixed(2)} п.п. доступности · перерыв ${m.max_outage_min} / ${base.max_outage_min} мин`;}

}
