import {EarthSurface} from './earth.js';
window.addEventListener('DOMContentLoaded',()=>{
 const app=window.kosmoApp;if(!app)return;
 const overview=document.getElementById('overviewEarth'),ctx=overview.getContext('2d');let surface;
 const draw=()=>{const r=overview.getBoundingClientRect();if(!r.width)return;const d=Math.min(devicePixelRatio||1,1.5);overview.width=r.width*d;overview.height=r.height*d;surface?.draw(ctx,overview.width,overview.height,Math.min(overview.width,overview.height)*.40,40,60);};surface=new EarthSurface(draw);new ResizeObserver(draw).observe(overview.parentElement);
 for(const el of document.querySelectorAll('input[type=range]')){const update=()=>el.style.setProperty('--range',`${(el.value-el.min)/(el.max-el.min)*100}%`);el.addEventListener('input',update);update();}
 const pin=document.getElementById('pinVariantBtn');
 pin.onclick=()=>{if(!app.simulationResult)return;app.comparisonMetric={...app.simulationResult.summary_metrics.C65};app.comparisonStage=app.simulationResult.effective_scenario.design.launch_stage;pin.textContent='Обновить точку сравнения';document.getElementById('comparisonResult').textContent='Вариант зафиксирован. Измените группировку в сцене.';};
 const map=app.map;new ResizeObserver(()=>map.resize()).observe(map.canvas.parentElement);
 const zoom=amount=>{const key=map.viewMode==='globe'?'globeZoom':map.viewMode==='polar'?'polarZoom':'flatZoom';map[key]=Math.max(.65,Math.min(3,map[key]*amount));map.render();};document.getElementById('zoomIn').onclick=()=>zoom(1.15);document.getElementById('zoomOut').onclick=()=>zoom(1/1.15);
 map.canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-'].includes(e.key)){e.preventDefault();if(e.key==='+')zoom(1.15);else if(e.key==='-')zoom(1/1.15);else{map.globeCenterLon+=e.key==='ArrowLeft'?-5:e.key==='ArrowRight'?5:0;map.globeCenterLat=Math.max(-85,Math.min(85,map.globeCenterLat+(e.key==='ArrowUp'?5:e.key==='ArrowDown'?-5:0)));map.render();}}});
 // Touch gestures use the same projection and camera as mouse controls.
 let touch=null;map.canvas.addEventListener('touchstart',e=>{if(e.touches.length===1){touch={x:e.touches[0].clientX,y:e.touches[0].clientY};}else if(e.touches.length===2){touch={distance:Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY)};}},{passive:true});
 map.canvas.addEventListener('touchmove',e=>{e.preventDefault();if(!touch)return;if(e.touches.length===2){const distance=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);if(touch.distance)zoom(distance/touch.distance);touch={distance};}else if(e.touches.length===1&&touch.x!=null){const t=e.touches[0],dx=t.clientX-touch.x,dy=t.clientY-touch.y;if(map.viewMode==='globe'){map.globeCenterLon-=dx*.35/map.globeZoom;map.globeCenterLat=Math.max(-85,Math.min(85,map.globeCenterLat+dy*.35/map.globeZoom));}else{const prefix=map.viewMode==='polar'?'polar':'flat';map[prefix+'PanX']+=dx*map.dpr;map[prefix+'PanY']+=dy*map.dpr;}touch={x:t.clientX,y:t.clientY};map.hasDragged=true;map.render();}},{passive:false});map.canvas.addEventListener('touchend',()=>touch=null);
 const top=document.querySelector('.scene-top');for(const [label,selector]of [['Орбиты','.left-panel'],['Терминалы','.right-panel']]){const b=document.createElement('button');b.textContent=label;b.className='btn mobile-panel-btn';b.style.display='none';b.setAttribute('aria-expanded','false');b.onclick=()=>{const panel=document.querySelector(selector),open=!panel.classList.contains('mobile-open');document.querySelectorAll('.control-panel').forEach(p=>p.classList.remove('mobile-open'));document.querySelectorAll('.mobile-panel-btn').forEach(p=>p.setAttribute('aria-expanded','false'));panel.classList.toggle('mobile-open',open);b.setAttribute('aria-expanded',String(open));};top.append(b);}
 document.addEventListener('visibilitychange',()=>{if(document.hidden)app.timeline.stop();});
 document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal-overlay.open,.mobile-open').forEach(n=>{n.classList.remove('open','mobile-open');});});
 // Stop the old hover handler from repainting the globe when using side panels.
 const render=map.render.bind(map);map.render=()=>{if(app.currentPage==='simulator'&&!document.hidden)render();};
 const modal=document.getElementById('modalSettings');modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-label','Параметры сценария');
 modal.querySelectorAll('button,select').forEach(n=>{if(!n.getAttribute('aria-label')&&n.id==='closeSettingsBtn')n.setAttribute('aria-label','Закрыть параметры');});
 document.getElementById('openSettingsBtn').addEventListener('click',()=>document.getElementById('closeSettingsBtn').focus());document.getElementById('closeSettingsBtn').addEventListener('click',()=>document.getElementById('openSettingsBtn').focus());
 modal.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const a=[...modal.querySelectorAll('button,input:not([type=file]),select')].filter(n=>n.offsetParent!==null);if(e.shiftKey&&document.activeElement===a[0]){e.preventDefault();a.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===a.at(-1)){e.preventDefault();a[0].focus();}});
});
